default_language_version:
    python: python3.11
default_stages:
    - commit
    - push
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-ast
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: detect-private-key
    -   id: mixed-line-ending
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, staging, --branch, production]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.270
    hooks:
    - id: ruff
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: 'v1.10.0'
    hooks:
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
-   repo: https://github.com/adamchainz/blacken-docs
    rev: "1.13.0"
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        - black
